"""empty message

Revision ID: d1545ee95edb
Revises: b8d6364b81a9
Create Date: 2024-01-24 11:01:43.029629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1545ee95edb'
down_revision = 'b8d6364b81a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date_ordered', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date_ordered')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
